[package]
name = "hvm"
version = "0.1.88"
edition = "2021"
description = "A lazy, beta-optimal, massively-parallel, non-garbage-collected and strongly-confluent functional compilation target."
repository = "https://github.com/Kindelia/HVM"
license = "MIT"
keywords = ["functional", "language", "runtime", "compiler", "target"]
categories = ["compilers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
test = true
crate-type = ["rlib"]

[[bin]]
name = "hvm"
test = false

[profile.dev_fast]
inherits = "dev"
opt-level = 3

[dependencies]
itertools = "0.10"
num_cpus = "1.13"
regex = "1.5.4"
highlight_error = "0.1.1"
clap = { version = "3.1.8", features = ["derive"] }
wasm-bindgen = "0.2.82"
web-sys = { version = "0.3", features = ["console"] }
instant = { version = "0.1", features = [ "wasm-bindgen", "inaccurate" ] }
ureq = { version = "2.5.0", default-features = false }

[dev-dependencies]
proptest = "1.0"

